export const brandFilters = [
  "Adidas",
  "Apple",
  "Aritzia",
  "Burberry",
  "Chanel",
  "Coach",
  "Gucci",
  "H&M",
  "Louis Vuitton",
  "Lululemon",
  "Nike",
  "Prada",
  "Rag & Bone",
  "Ralph Lauren",
  "Ray-Ban",
  "Sephora",
  "Tiffany & Co.",
  "Uniqlo",
  "Zara",
  "Birkenstock",
  "COS",
  "Patagonia",
  "Vuori",
  "Abercrombie & Fitch",
  "GUESS",
  "J.Crew",
  "Allbirds",
  "UGG",
  "BYREDO",
  "CELINE",
  "Free People",
  "Moschino",
  "Dr. Martens",
  "Joybird",
  "EILEEN FISHER",
  "Bared Footwear",
  "Bonpoint",
  "7 For All Mankind",
  "Luca Faloni",
  "Jonathan Adler",
  "Technogym",
  "Thom Sweeney",
  "Fred Perry",
  "Yohji Yamamoto",
  "Isabel Marant",
  "FRAME",
  "Theory",
  "STAUD",
  "Stone Island",
  "Acne Studios",
  "Fjällräven",
  "BAGGU",
  "Gudrun Sjödén",
  "Rails",
  "Suitsupply",
  "Off-White",
  "Zadig & Voltaire",
  "Orlebar Brown",
  "Polène",
  "MUJI",
  "Vince",
  "Paper Planes",
  "Club Monaco",
  "SCHUTZ",
  "Swarovski",
  "SKECHERS",
  "Edikted",
  "Intimissimi",
  "Brandy Melville",
  "TUMI",
  "Windsor",
  "Proper Cloth",
  "Levi's",
  "Dolce Vita",
  "Badichi",
  "IRO",
  "Paloma Wool",
  "Blundstone",
  "Fueguia 1833",
  "Champion",
  "Naked & Famous",
  "Alexander Wang",
  "Billionaire Boys Club",
  "Stone and Strand",
  "Madhappy",
  "TOTEME",
  "KEETSA",
  "GANNI",
  "F.P.Journe",
  "Parajumpers",
  "Golden Goose",
  "Rouje",
  "COCO-MAT",
  "MOUSSY",
  "Ron Dorff",
  "Merz b. Schwanen",
  "Knickerbocker",
  "Classic Football Shirts",
  "John Fluevog",
  "Alexis Bittar",
  "Converse",
  "Banana Republic",
  "MANGO",
  "Herschel Supply",
  "Lacoste",
  "Frankies Bikinis",
  "Retrofête",
  "Alo",
  "Sam Edelman",
  "Hive & Colony",
  "Y-3",
  "Journelle",
  "Agent Provocateur",
  "A.P.C.",
  "RIMOWA",
  "Falconeri",
  "Miu Miu",
  "Tory Burch",
  "Dyson",
  "Marni",
  "BAPE",
  "SIMKHAI",
  "LANVIN",
  "Wilson",
  "APL",
  "Maje",
  "With Clarity",
  "Aviator Nation",
  "Saint Laurent",
  "Guizio",
  "Mackage",
  "Monica Vinader",
  "Thuma",
  "Marimekko",
  "JACQUEMUS",
  "Gerard Darel",
  "FANA",
  "Berta",
  "Tibi",
  "Wolford",
  "John Hardy",
  "Slowear",
  "David Yurman",
  "AG Jeans",
  "Dior",
  "Camper",
  "FARM Rio",
  "Marc Jacobs",
  "Faherty",
  "Amsale",
  "Carl Hansen & Søn",
  "Galia Lahav",
  "Sporty & Rich",
  "Safavieh",
  "Anthropologie",
  "Crockett & Jones",
  "Reiss",
  "The Frankie Shop",
  "Malbon Golf",
  "The Citizenry",
  "Foscarini",
  "David Roytman",
  "Grace Loves Lace",
  "Avitto",
  "Acustom Apparel",
  "AX Armani Exchange",
  "Timberland",
  "American Eagle",
  "The North Face",
  "JBL",
  "Garage",
  "RAINS",
  "Arc'teryx",
  "  Cotton On",
  "MAC Cosmetics",
  "Bonobos",
  "Rick Owens",
  "Harley-Davidson",
  "Pandora",
  "& Other Stories",
  "KENZO",
  "KHAITE",
  "Moncler",
  "Brunello Cucinelli",
  "Valentino",
  "Stella McCartney",
  "Cartier",
  "MCM",
  "alice + olivia",
  "Bang & Olufsen",
  "DIESEL",
  "Reformation",
  "Kate Spade",
  "Evisu",
  "LeSportsac",
  "Ksubi",
  "Nanushka",
  "Bottega Veneta",
  "Chloe",
  "Drake's",
  "Ferragamo",
  "Herno",
  "Longchamp",
  "LOEWE",
  "Nordic Knots",
  "Norrøna",
  "Paul Smith",
  "PLEATS PLEASE ISSEY MIYAKE",
  "Burton",
  "Alexander McQueen",
  "Cult Gaia",
  "Moose Knuckles",
  "A.L.C.",
  "ZIMMERMANN",
  "Hästens",
  "Tom Dixon",
  "Anita Dongre",
  "Outerknown",
  "nanamica",
  "Ted Baker",
  "Canada Goose",
  "Grand Seiko",
  "Cire Trudon",
  "Burrow",
  "American Giant",
  "G-Shock",
  "Rapha",
  "MacKenzie-Childs",
  "Salomon",
];

export const categoryFilters = [
  "Luxury Fashion",
  "Contemporary Fashion",
  "Athletic & Streetwear",
  "Accessories & Jewelry",
  "Beauty & Cosmetics",
  "Electronics",
  "Books & Stationery",
  "Home & Design",
  "Food & Beverage",
  "Art & Culture",
  "Musical Instruments",
  "Off-Price Retail",
  "Fragrance & Candles",
  "Gifts & Souvenirs",
  "Children's Retail",
  "Eyewear & Optical",
  "Lingerie & Intimates",
  "Luggage & Travel",
  "Custom Apparel",
  "Hardware & Home Improvement",
  "Asian Goods",
  "Denim Specialty",
  "Sustainable Fashion",
  "Vintage & Consignment",
  "Wellness & Pharmacy",
  "Bridal & Wedding",
  "Swimwear",
  "Sporting Goods",
];
