export const brandFilters = [
  "Adidas",
  "Apple",
  "Aritzia",
  "Balenciaga",
  "Burberry",
  "Chanel",
  "Coach",
  "Fendi",
  "Gucci",
  "H&M",
  "Hermès",
  "Louis Vuitton",
  "Lululemon",
  "Nike",
  "Prada",
  "Rag & Bone",
  "Ralph Lauren",
  "Ray-Ban",
  "Sephora",
  "Tiffany & Co.",
  "Uniqlo",
  "Zara",
  "Birkenstock",
  "COS",
  "Patagonia",
  "Vuori",
  "Abercrombie & Fitch",
  "GUESS",
  "J.Crew",
  "Allbirds",
  "Glossier",
  "Bloomingdale's",
  "MINISO",
  "UGG",
  "REI",
  "Everlane",
  "Gentle Monster",
  "BYREDO",
  "CELINE",
  "Free People",
  "Moschino",
  "Dr. Martens",
  "Joybird",
  "EILEEN FISHER",
  "Bared Footwear",
  "Bonpoint",
  "7 For All Mankind",
  "Luca Faloni",
  "Jonathan Adler",
  "Technogym",
  "Thom Sweeney",
  "Calligaris",
  "Fred Perry",
  "Yohji Yamamoto",
  "Isabel Marant",
  "FRAME",
  "Theory",
  "STAUD",
  "Stone Island",
  "Acne Studios",
  "Fjällräven",
  "BAGGU",
  "Flou",
  "Artemide",
  "Gudrun Sjödén",
  "Savoir",
  "Rails",
  "Suitsupply",
  "Off-White",
  "Zadig & Voltaire",
  "Orlebar Brown",
  "Polène",
  "T.J. Maxx",
  "ECCO",
  "MUJI",
  "Stadium Goods",
  "Sézane",
  "Diptyque",
  "Cuyana",
  "Rixo",
  "Vince",
  "Ana Luisa",
  "VEJA",
  "Kiehl's",
  "Mejuri",
  "ELOREA",
  "Vuarnet",
  "Aimé Leon Dore",
  "DITA",
  "Zegna",
  "Paper Planes",
  "LIVELY",
  "Club Monaco",
  "SCHUTZ",
  "Swarovski",
  "SKECHERS",
  "Edikted",
  "Intimissimi",
  "Brandy Melville",
  "TUMI",
  "Windsor",
  "Proper Cloth",
  "Levi's",
  "Dolce Vita",
  "Badichi",
  "IRO",
  "Paloma Wool",
  "Blundstone",
  "Indochino",
  "Lauren Manoogian",
  "Catbird",
  "Modern Citizen",
  "Paper Source",
  "Fueguia 1833",
  "Champion",
  "Naked & Famous",
  "Alexander Wang",
  "Courrèges",
  "Billionaire Boys Club",
  "CB2",
  "Stone and Strand",
  "Purple Brand",
  "Madhappy",
  "TOTEME",
  "KEETSA",
  "GANNI",
  "CHIMI",
  "F.P.Journe",
  "Parajumpers",
  "Ochre",
  "Golden Goose",
  "Rouje",
  "The Great",
  "COCO-MAT",
  "MOUSSY",
  "Ron Dorff",
  "Fritz Hansen",
  "Merz b. Schwanen",
  "Knickerbocker",
  "Classic Football Shirts",
  "Farrow & Ball",
  "NN.07",
  "John Fluevog",
  "Alexis Bittar",
  "Converse",
  "Banana Republic",
  "MANGO",
  "Herschel Supply",
  "Lacoste",
  "Frankies Bikinis",
  "Retrofête",
  "Alo",
  "Sam Edelman",
  "Hive & Colony",
  "Y-3",
  "Givenchy",
  "ME+EM",
  "Journelle",
  "Agent Provocateur",
  "A.P.C.",
  "RIMOWA",
  "Falconeri",
  "Miu Miu",
  "ALAÏA",
  "Tory Burch",
  "Dyson",
  "Marni",
  "BAPE",
  "SIMKHAI",
  "LANVIN",
  "Wilson",
  "APL",
  "Maje",
  "With Clarity",
  "Aviator Nation",
  "Saint Laurent",
  "Veronica Beard",
  "Guizio",
  "Mackage",
  "Monica Vinader",
  "Thuma",
  "Marimekko",
  "JACQUEMUS",
  "Gerard Darel",
  "Susan Lazar",
  "Salvatori",
  "Mulberry",
  "FANA",
  "Berta",
  "Tibi",
  "Wolford",
  "John Hardy",
  "Slowear",
  "David Yurman",
  "AG Jeans",
  "Dior",
  "Camper",
  "FARM Rio",
  "ba&sh",
  "Marc Jacobs",
  "Faherty",
  "Amsale",
  "Carl Hansen & Søn",
  "Galia Lahav",
  "Sporty & Rich",
  "Jenni Kayne",
  "Safavieh",
  "Anthropologie",
  "The Ordinary",
  "Crockett & Jones",
  "Reiss",
  "Coclico",
  "Marine Layer",
  "Peak Design",
  "StockX",
  "State & Liberty",
  "OAK + FORT",
  "The Frankie Shop",
  "MZ Wallace",
  "Malbon Golf",
  "The Citizenry",
  "Parachute",
  "Foscarini",
  "David Roytman",
  "Sea New York",
  "Montauk Sofa",
  "FOUNDRAE",
  "On",
  "Maria Tash",
  "Grace Loves Lace",
  "Malia Mills",
  "Avitto",
  "Acustom Apparel",
  "What Goes Around Comes Around",
];

export const categoryFilters = [
  "Luxury Fashion",
  "Contemporary Fashion",
  "Athletic & Streetwear",
  "Accessories & Jewelry",
  "Beauty & Cosmetics",
  "Electronics",
  "Books & Stationery",
  "Home & Design",
  "Food & Beverage",
  "Art & Culture",
  "Musical Instruments",
  "Off-Price Retail",
  "Fragrance & Candles",
  "Gifts & Souvenirs",
  "Children's Retail",
  "Eyewear & Optical",
  "Lingerie & Intimates",
  "Luggage & Travel",
  "Custom Apparel",
  "Hardware & Home Improvement",
  "Art Supplies",
  "Asian Goods",
  "Denim Specialty",
  "Lighting",
  "Home Appliances",
  "Sustainable Fashion",
  "Vintage & Consignment",
  "Pet Services & Supplies",
  "Wellness & Pharmacy",
  "Bridal & Wedding",
  "Swimwear",
];
