name: CI/CD

on:
    push:
        branches: [main, master, github-actions]
    pull_request:
            branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}
      - name: Cache backend dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-backend-node-modules-${{ hashFiles('backend/package-lock.json') }}
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install
      - name: Lint frontend code
        working-directory: ./frontend
        run: npm run lint
      - name: Lint backend code
        working-directory: ./backend
        run: npm run lint

  build:
    env:
      DATABASE_URL: ${{ secrets.MONGO_URI }}
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install
      - name: Build frontend project
        working-directory: ./frontend
        run: npm run build

  test:
    env:
      DATABASE_URL: ${{ secrets.MONGO_URI }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Cache backend dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-backend-node-modules-${{ hashFiles('backend/package-lock.json') }}
      - name: Install dependencies
        working-directory: ./backend
        run: npm install
      - name: Run tests
        working-directory: ./backend
        run: npm run test
